APP     = sign
OBJS    = sign.o 
SRCTOP  = ${VPATH}/../..
BLDTOP  = ../..
CFLAGS += -I${SRCTOP}/dyncall
LDLIBS += -L${BLDTOP}/dyncall -ldyncall_s 
CFLAGS += -O3
.PHONY: all clean install 
all: ${APP}
${APP}: ${OBJS} 
	${CC} ${CFLAGS} ${LDFLAGS} ${OBJS} ${LDLIBS} -o ${APP} 
clean:
	rm -f ${APP} ${OBJS}
install:
	mkdir -p ${PREFIX}/test
	cp ${APP} ${PREFIX}/test
