APP       = resolve_self
OBJS      = main.o
SRCTOP    = ${VPATH}/../..
BLDTOP    = ../..
CFLAGS   += -I${SRCTOP}/dynload
LDFLAGS  += -rdynamic
LDLIBS_D  = -L${BLDTOP}/dynload -ldynload_s 
.PHONY: all clean install
all: ${APP}
${APP}: ${OBJS} 
	${CC} ${CFLAGS} ${LDFLAGS} ${OBJS} ${LDLIBS_D} ${LDLIBS} -o ${APP}
clean:
	rm -f ${APP} ${OBJS}
install:
	mkdir -p ${PREFIX}/test
	cp ${APP} ${PREFIX}/test

