APP = plain
OBJS = test_main.o test_structs.o

TOP      = ../..
CFLAGS  += -I${TOP}/dyncall
LDFLAGS += -L${TOP}/dyncall
LDLIBS  += -ldyncall_s

all: ${APP}

.PHONY: all clean install

${APP}: ${OBJS} 
	${CC} ${OBJS} ${LDFLAGS} ${LDLIBS} -o ${APP}

clean:
	rm -f ${APP} ${OBJS}

