# -*- coding: utf-8 -*-
#
# SCons build system
# Copyright (C) 2009 Tim Blechmann
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; see the file COPYING.  If not, write to
# the Free Software Foundation, Inc., 59 Temple Place - Suite 330,
# Boston, MA 02111-1307, USA.

Import("env")

sources = Split("""
BeatTrack2.cpp
BeatTrack.cpp
BinaryOpUGens.cpp
ChaosUGens.cpp
Convolution.cpp
DelayUGens.cpp
DemandUGens.cpp
DiskIO_UGens.cpp
DynNoiseUGens.cpp
FeatureDetection.cpp
FFT2InterfaceTable.cpp
FFTInterfaceTable.cpp
FFT_UGens.cpp
FilterUGens.cpp
GendynUGens.cpp
GrainUGens.cpp
IOUGens.cpp
KeyboardUGens.cpp
KeyTrack.cpp
LFUGens.cpp
Loudness.cpp
MFCC.cpp
ML.cpp
ML_SpecStats.cpp
MouseUGens.cpp
MulAddUGens.cpp
NoiseUGens.cpp
Onsets.cpp
OscUGens.cpp
PanUGens.cpp
PartitionedConvolution.cpp
PhysicalModelingUGens.cpp
PV_ThirdParty.cpp
PV_UGens.cpp
ReverbUGens.cpp
SCComplex.cpp
TestUGens.cpp
TriggerUGens.cpp
UnaryOpUGens.cpp
UnpackFFTUGens.cpp
""")

sources = [File(x, "supercollider/Source/plugins") for x in sources]

pluginenv = env.Clone()

pluginenv.Append(CPPDEFINES=['SUPERNOVA'])

plugins = []

for source in sources:
    plugin_name = source.abspath.split('/')[-1][:-4]
    plugin = pluginenv.SharedLibrary(plugin_name, source,
                                CPPPATH=["supercollider/Headers/plugin_interface",
                                         "supercollider/Headers/server",
                                         "supercollider/Headers/common",
                                         "#source",
                                         "#libs/boost",
                                         "#libs/boost_lockfree",
                                        ],
                                SHLIBPREFIX="",
                                )
    plugins.append(plugin)

Return("plugins")
