#include "tokens.hpp"

[[nodiscard]] const char* sc::lex::to_string(TokenType t) noexcept {
    switch (t) {
    case TokenType::EndOfFile:
        return "EndOfFile";
    case TokenType::Name:
        return "Name";
    case TokenType::ClassName:
        return "ClassName";
    case TokenType::PrimitiveName:
        return "PrimitiveName";
    case TokenType::Integer:
        return "Integer";
    case TokenType::IntegerRadix:
        return "IntegerRadix";
    case TokenType::Hexidecimal:
        return "Hexidecimal";
    case TokenType::Float:
        return "Float";
    case TokenType::FloatRadix:
        return "FloatRadix";
    case TokenType::FloatExponent:
        return "FloatExponent";
    case TokenType::Pi:
        return "Pi";
    case TokenType::Inf:
        return "Inf";
    case TokenType::AccidentalSteps:
        return "AccidentalSteps";
    case TokenType::AccidentalCents:
        return "AccidentalCent";
    case TokenType::SymbolSlash:
        return "SymbolSlash";
    case TokenType::SymbolQuote:
        return "SymbolQuote";
    case TokenType::Ascii:
        return "Ascii";
    case TokenType::True:
        return "True";
    case TokenType::False:
        return "False";
    case TokenType::Nil:
        return "Nil";
    case TokenType::StringLine:
        return "StringLine";
    case TokenType::While:
        return "While";
    case TokenType::Var:
        return "Var";
    case TokenType::Arg:
        return "Arg";
    case TokenType::ClassVar:
        return "ClassVar";
    case TokenType::Const:
        return "Const";
    case TokenType::OpenParen:
        return "OpenParen";
    case TokenType::OpenSquare:
        return "OpenSquare";
    case TokenType::OpenCurly:
        return "OpenCurly";
    case TokenType::BeginClosedFunction:
        return "BeginClosedFunction";
    case TokenType::CloseParen:
        return "CloseParen";
    case TokenType::CloseSquare:
        return "CloseSquare";
    case TokenType::CloseCurly:
        return "CloseCurly";
    case TokenType::SemiColon:
        return "SemiColon";
    case TokenType::Colon:
        return "Colon";
    case TokenType::Comma:
        return "Comma";
    case TokenType::EqualsSign:
        return "EqualsSign";
    case TokenType::NonLocalReturn:
        return "NonLocalReturn";
    case TokenType::BackTick:
        return "BackTick";
    case TokenType::Tilde:
        return "Tilde";
    case TokenType::Hash:
        return "Hash";
    case TokenType::LeftArrow:
        return "LeftArrow";
    case TokenType::Ellipsis:
        return "Ellipsis";
    case TokenType::Dot:
        return "Dot";
    case TokenType::DotDot:
        return "DotDot";
    case TokenType::CurryArg:
        return "CurryArg";
    case TokenType::Pipe:
        return "Pipe";
    case TokenType::ReadWriteVar:
        return "ReadWriteVar";
    case TokenType::Minus:
        return "Minus";
    case TokenType::Multiply:
        return "Multiply";
    case TokenType::Add:
        return "Add";
    case TokenType::LessThan:
        return "LessThan";
    case TokenType::GreaterThan:
        return "GreaterThan";
    case TokenType::BinaryOperator:
        return "BinaryOperator";
    case TokenType::KeywordBinaryOperator:
        return "KeywordBinaryOperator";
    case TokenType::Space:
        return "Space";
    case TokenType::NewLine:
        return "NewLine";
    case TokenType::Tab:
        return "Tab";
    case TokenType::Comment:
        return "Comment";
    case TokenType::MultilineComment:
        return "MultilineComment";
    case TokenType::ErUnexpected:
        return "ErUnexpected";
    case TokenType::ErSymbolQuoteUnclosed:
        return "ErSymbolQuoteUnclosed";
    case TokenType::ErMultilineCommentUnclosed:
        return "ErMultilineCommentUnclosed";
    case TokenType::ErStringUnclosed:
        return "ErStringUnclosed";
    case TokenType::ErMissingExponent:
        return "ErMissingExponent";
    case TokenType::ErInvalidToken:
        return "ErInvalidToken";
    case TokenType::ErInvalidUTF8:
        return "ErInvalidUTF8";
    case TokenType::ErUnknown:
        return "ErUnknown";
    default:
        return "Unknown token";
    }
}
