# path to default libc.so file, easier to do via shell than in code (see main() in dynload_plain.c)
# for compat: first gmake style, then assignment op which will use ! as part of var name on gmake<4
#             and thus not override previously set var
DEF_C_DYLIB=$(shell ((ls /lib*/libc.so* || ls /usr/lib/libc.so*) | (sort -V -r || sort -t . -n -k 2)) 2>/dev/null | head -1)
DEF_C_DYLIB!=((ls /lib*/libc.so* || ls /usr/lib/libc.so*) | (sort -V -r || sort -t . -n -k 2)) 2>/dev/null | head -1

APP       = dynload_plain
OBJS      = dynload_plain.o
SRCTOP    = ${VPATH}/../..
BLDTOP    = ../..
CFLAGS   += -I${SRCTOP}/dynload -DDEF_C_DYLIB=\"${DEF_C_DYLIB}\"
LDLIBS_D += -L${BLDTOP}/dynload -ldynload_s

# Works on: Darwin, NetBSD.
# Linux: add '-ldl'
.PHONY: all clean install
all: ${APP}
${APP}: ${OBJS}
	${CC} ${LDFLAGS} ${OBJS} ${LDLIBS_D} ${LDLIBS} -o ${APP}
clean:
	rm -f ${APP} ${OBJS}
install:
	mkdir -p ${PREFIX}/test
	cp ${APP} ${PREFIX}/test

