APP = suite2_x86win32std
OBJS = case.o main.o

TOP     = ../..
CFLAGS  = -I${TOP}/dyncall
LDFLAGS = -L${TOP}/dyncall
LDLIBS  = -ldyncall_s
LINK    = ${CXX}

all: ${APP}

.PHONY: all clean install

RM      ?= rm -f
AR      ?= ar
MKDIR   ?= mkdir
INSTALL ?= install -p

${APP}: ${OBJS} 
	${LINK} ${OBJS} ${LDFLAGS} ${LDLIBS} -o ${APP} ${TARGET_ARCH}

clean:
	${RM} ${APP} ${OBJS}

