APP  = suite_floats
OBJS = case.o main.o
TOP      = ../..
CFLAGS  += -I${TOP}/dyncall
LDFLAGS += -L${TOP}/dyncall
LDLIBS  += -ldyncall_s

all: ${APP}


.PHONY: all clean 

${APP}: ${OBJS} 
	${CXX} ${OBJS} ${LDFLAGS} ${LDLIBS} -o ${APP}

clean:
	rm -f ${APP} ${OBJS}

