#! /bin/sh
# This takes the build products and makes a distribution folder.
mkdir SuperCollider_f
cp -R SuperCollider3Service/build/SCService.app SuperCollider_f
cd build
cp -R examples SCClassLibrary Help plugins synthdefs sounds scsynth SuperCollider.app ../SuperCollider_f
cd ..
cd SuperCollider_f
mkdir recordings
rm -r */CVS */*/CVS */*/*/CVS */*/*/*/CVS */*/*/*/*/CVS
