#!/bin/sh

DATE=`date "+%Y-%m-%d"`

if [ -d SuperCollider-source ]; then
	echo "Please remove the ./SuperCollider-source directory before running this script."
	exit 1
fi

mkdir SuperCollider-source
svn export --force ../ SuperCollider-source
cp -Rp optional SuperCollider-source/optional
tar cvfz "SuperCollider-source-$DATE.tar.gz" SuperCollider-source
rm -rf SuperCollider-source
