#!/bin/sh

DATE=`date "+%Y-%m-%d"`

if [ -d SuperCollider ]; then
	echo "Please remove the ./SuperCollider directory before running this script."
	exit 1
fi

svn export --force ../build SuperCollider
cp -R ../build/SuperCollider.app ../build/scsynth ../build/sclang SuperCollider
cp ../build/plugins/* SuperCollider/plugins/
find SuperCollider/help/ \( -name "*.htm" -or -name "*.html" \) -exec /Developer/Tools/SetFile -c SCjm {} \;
./pkg-dmg --source ./SuperCollider --target "SuperCollider-$DATE.dmg" --sourcefile --volname SuperCollider --mkdir /.background --copy background.png:/.background/background.png --copy dmg.ds_store:/.DS_Store --symlink /Applications:/Applications --copy optional/:"/Optional Installs"
rm -rf ./SuperCollider
