#!/bin/bash

if [ $# -ne "3" ] 
then
   echo "Usage: `basename $0` plugin_name component_type component_subtype 
   plugin_name is the name of your synthdef file minus the extension, ie plugin_name.scsyndef is your synth definition file. 
   component_subtype must be a four chars code, like PLUG. It sould be unique in your system within all SCAU generated plugins"
   exit
fi
echo $1 
sed -e "s/@@NAME@@/$1/" -e "s/@@COMP_TYPE@@/$2/" -e "s/@@COMP_SUBTYPE@@/$3/" SuperColliderAU.r>tmp.r
cp -R SuperColliderAU.component/ $1.component/
mkdir -p $1.component/Contents/Resources/synthdefs
cp pluginSpec.plist $1.component/Contents/Resources/
cp serverConfig.plist $1.component/Contents/Resources/
cp $1.scsyndef $1.component/Contents/Resources/synthdefs
/Developer/Tools/Rez -d i386_YES -d ppc_YES -o $1.component/Contents/Resources/SuperColliderAU.rsrc -useDF \
-I /System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Versions/A/Headers \
-I /Developer/Examples/CoreAudio/AudioUnits/AUPublic/AUBase tmp.r

rm tmp.r
rm $1.scsyndef
rm pluginSpec.plist
rm serverConfig.plist