#!/bin/sh

EXTRA_CMAKE_FLAGS=

if $USE_SYSLIBS; then
    EXTRA_CMAKE_FLAGS="-DSYSTEM_BOOST=ON -DSYSTEM_YAMLCPP=ON"
fi

if $SHARED_LIBSCSYNTH; then
    EXTRA_CMAKE_FLAGS="-DLIBSCSYNTH=ON $EXTRA_CMAKE_FLAGS"
fi

cmake -G"Xcode" \
    -DRULE_LAUNCH_COMPILE=ccache \
    -DCMAKE_PREFIX_PATH=`brew --prefix qt5` \
    -DCMAKE_OSX_DEPLOYMENT_TARGET=10.10 \
    -DSUPERNOVA=ON \
    $EXTRA_CMAKE_FLAGS \
    $TRAVIS_BUILD_DIR --debug-output
