#!/bin/sh
# =====================================================================
# file:		bootstrap
# contents:	build system bootstrap script
# author:	stefan kersten <steve@k-hornz.de>
# CVS:		$Id$
# =====================================================================

bootstrap="${PWD}/linux/bootstrap"

if test ! -f "$bootstrap"; then
    echo "run ./linux/bootstrap from the top source directory"
    exit 1
fi

do_bootstrap()
{
    set -x
    aclocal \
	&& libtoolize --automake --force \
	&& autoheader \
	&& automake --add-missing --foreign \
	&& autoconf
}

do_bootstrap

# EOF
