APP       = suite2
OBJS      = case.o main.o
SRCTOP    = ${VPATH}/../..
BLDTOP    = ../..
CXXFLAGS += -I${SRCTOP}/dyncall
LDLIBS   += -L${BLDTOP}/dyncall -ldyncall_s
.PHONY: all clean configure install
all: ${APP}
${APP}: ${OBJS} 
	${CXX} ${CXXFLAGS} ${LDFLAGS} ${OBJS} ${LDLIBS} -o ${APP} 
clean:
	rm -f ${APP} ${OBJS}
configure:
	python mkcase.py 1>case.h 2>config.h
install:
	mkdir -p ${PREFIX}/test
	cp ${APP} ${PREFIX}/test

