APP  = suite2
OBJS = case.o main.o

TOP      = ../..
CFLAGS  += -I${TOP}/dyncall
LDFLAGS += -L${TOP}/dyncall
LDLIBS  += -ldyncall_s

all: ${APP}


.PHONY: all clean autogen

${APP}: ${OBJS} 
	${CXX} ${OBJS} ${LDFLAGS} ${LDLIBS} -o ${APP} 

clean:
	rm -f ${APP} ${OBJS}

autogen:
	python mkcase.py 1>case.h 2>config.h
