APP = syscall
OBJS = syscall.o

SRCTOP   = ../..
BLDTOP   = ../..
CFLAGS  += -I${SRCTOP}/dyncall
LDFLAGS += -L${BLDTOP}/dyncall
LDLIBS  += -ldyncall_s
LINK     = ${CC}

all: ${APP}

.PHONY: all clean 

${APP}: ${OBJS} 
	${CC} ${OBJS} ${LDFLAGS} ${LDLIBS} -o ${APP} 

clean:
	rm -f ${APP} ${OBJS}

