file(TO_NATIVE_PATH ${SC_INSTALL_PREFIX} NATIVE_INSTALL_PREFIX)

execute_process( COMMAND makensis
    /DSC_VERSION=${SC_VERSION}
    /DSC_INSTALL_ROOT="${NATIVE_INSTALL_PREFIX}"
    # FIXME: Does not support spaces in path:
    /DSC_DST_DIR=${NATIVE_INSTALL_PREFIX}
    /DSC_ICON=${SC_CUBE_PATH}
    /DFILE_NAME_SUFIX=${BUILD_DEF}
    /DTARCH=${TARGET_ARCH}
    ${NSIS_SCRIPT}
)
