#!/bin/sh
# =====================================================================
# file:		bootstrap
# contents:	build system bootstrap script
# author:	stefan kersten <steve@k-hornz.de>
# CVS:		$Id$
# =====================================================================

bootstrap="${PWD}/linux/bootstrap"

if test ! -f "$bootstrap"; then
    echo "run ./linux/bootstrap from the top source directory"
    exit 1
fi

do_bootstrap()
{
    set -x
    aclocal \
	&& libtoolize --automake --force \
	&& autoheader \
	&& automake --add-missing --foreign \
	&& autoconf
    set +x
}

# case "$1" in
#     server|lang)
# 	echo "* bootstrapping server/lang"
# 	do_bootstrap
# 	;;
#     plugins)
# 	if test -d source/plugins; then
# 	    echo "* bootstrapping plugins"
# 	    cd source/plugins && do_bootstrap
# 	else
# 	    echo "directory source/plugins not found"
# 	    exit 1
# 	fi
# 	;;
#     *)
# 	"$bootstrap" server
# 	"$bootstrap" plugins
# 	;;
# esac

do_bootstrap

# EOF
