#!/bin/sh
# =====================================================================
# file:		bootstrap
# contents:	build system bootstrap script
# author:	stefan kersten <steve@k-hornz.de>
# CVS:		$Id$
# =====================================================================

top_dir=$PWD
bootstrap=`basename $0`

set -x

aclocal \
&& libtoolize --automake --force \
&& autoheader \
&& automake --add-missing --foreign \
&& autoconf

if [ -d source/plugins ]; then
    cd source/plugins && $top_dir/linux/$bootstrap
fi

# EOF
