name: Lint non-code files
on:
  push:
    paths:
      - 'examples/**'
      - 'HelpSource/**'
      - 'sounds/**'
      - '*.md'
  pull_request:
    paths:
      - 'examples/**'
      - 'HelpSource/**'
      - 'sounds/**'
      - '*.md'

jobs:
  lint-non-code-files:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: lint class library
        run: |
          sudo npm install -g lintspaces-cli
          lintspaces -e .editorconfig SCClassLibrary/**/*.sc || true # ignore failure

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - uses: pre-commit/action@v3.0.1
        name: 'Run pre-commit'
        env:
          FULL_CHECK: 1
