name: SClang Error Regression
on:
  workflow_call:
    inputs:
      sc-version:
        required: true
        type: string
jobs:
  sclang-error-regression:
    runs-on: ubuntu-26.04
    env:
      INSTALL_PATH: ${{ github.workspace }}/build/Install
      ARTIFACT_FILE: "SuperCollider-${{ inputs.sc-version }}-ubuntu-26.04-gcc16"
      SCLANG: ${{ github.workspace }}/build/Install/bin/sclang
      CLASS_LIB: ${{ github.workspace }}/SCClassLibrary
      ERROR_REGRESSION: ${{ github.workspace }}/testsuite/sclangErrorRegressions
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: false # don't need submodules for testing

      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          name: ${{ env.ARTIFACT_FILE }}
          path: ${{ env.INSTALL_PATH }}

      - name: Extract artifact
        run: |
          cd "$INSTALL_PATH"
          echo Contents of `pwd`:
          ls
          unzip $ARTIFACT_FILE.zip

      - name: Setup environment
        run: |
          # install dependencies
          sudo apt-get update
          sudo apt-get install --yes libsndfile1 libavahi-client-dev libfftw3-dev libicu-dev libudev-dev qt6-base-dev libqt6svg6-dev qt6-webengine-dev libqt6webenginecore6-bin jackd1 socat

          # add bin to PATH so that scsynth can be found
          echo "$INSTALL_PATH/bin" >> $GITHUB_PATH

          # start jack
          jackd --no-realtime --silent -d dummy &

          # start virtual display server
          export DISPLAY=:99
          echo "DISPLAY=$DISPLAY" >> $GITHUB_ENV
          Xvfb $DISPLAY -screen 0 1024x768x16 &
          
      - name: Create File
        shell: bash
        continue-on-error: false
        env:
          QTWEBENGINE_CHROMIUM_FLAGS: "--no-sandbox --disable-gpu"
          LIBGL_ALWAYS_SOFTWARE: "1"
        run: |
          cd ${{ github.workspace }}
          timeout 5m $SCLANG -a --include-path SCClassLibrary --include-path testsuite/sclangErrorRegressions testsuite/sclangErrorRegressions/generateError.scd ${{ github.workspace }}/build/regression.txt

      - name: Check for differences
        shell: bash
        run: |
          diff $ERROR_REGRESSION/regression.txt ${{ github.workspace }}/build/regression.txt --unified --color
