name: Test Linux
on:
  workflow_call:
    inputs:
      sc-version:
        required: true
        type: string

jobs:
  test-linux:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    env:
      INSTALL_PATH: ${{ github.workspace }}/build/Install
      ARTIFACT_FILE: "SuperCollider-${{ inputs.sc-version }}-ubuntu-22.04-gcc12"
      SCLANG: ${{ github.workspace }}/build/Install/bin/sclang
      SCRIPT_RUN_TESTS: ${{ github.workspace }}/testsuite/scripts/run_classlibrary_unittest_for_gha.scd
      INCLUDE_TEST: ${{ github.workspace }}/testsuite/classlibrary
      INCLUDE_CLASSLIB: ${{ github.workspace }}/SCClassLibrary

    steps:
      - uses: actions/checkout@v7
        with:
          submodules: false # don't need submodules for testing

      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          name: ${{ env.ARTIFACT_FILE }}
          path: ${{ env.INSTALL_PATH }}

      - name: Extract artifact
        run: |
          cd "$INSTALL_PATH"
          echo Contents of `pwd`:
          ls
          unzip $ARTIFACT_FILE.zip

      - name: Setup environment
        run: |
          # install dependencies
          sudo apt-get update
          sudo apt-get install --yes libsndfile1 libavahi-client-dev libfftw3-dev libicu-dev libudev-dev qt6-base-dev libqt6svg6-dev qt6-webengine-dev libqt6webenginecore6-bin jackd1 socat

          # add bin to PATH so that scsynth can be found
          echo "$INSTALL_PATH/bin" >> $GITHUB_PATH

          # start jack
          jackd --no-realtime --silent -d dummy &

          # start virtual display server
          export DISPLAY=:99
          echo "DISPLAY=$DISPLAY" >> $GITHUB_ENV
          Xvfb $DISPLAY -screen 0 1024x768x16 &

      - name: Run tests
        shell: bash
        run: $SCLANG --exclude-default-paths --include-path $INCLUDE_TEST --include-path $INCLUDE_CLASSLIB $SCRIPT_RUN_TESTS

     