name: Test Windows
on:
  workflow_call:
    inputs:
      sc-version:
        required: true
        type: string

jobs:
  test-windows:
    runs-on: windows-2022
    timeout-minutes: 30
    env:
      INSTALL_PATH: ${{ github.workspace }}/build/Install
      ARTIFACT_FILE: "SuperCollider-${{ inputs.sc-version }}-win64"
      TESTS_PATH: ${{ github.workspace }}/testsuite/classlibrary
      SCLANG: ${{ github.workspace }}/build/Install/SuperCollider/sclang
      SCRIPT_RUN_TESTS: ${{ github.workspace }}/testsuite/scripts/run_classlibrary_unittest_for_gha.scd
      INCLUDE_TEST: ${{ github.workspace }}/testsuite/classlibrary
      INCLUDE_CLASSLIB: ${{ github.workspace }}/SCClassLibrary     

    steps:
      - uses: actions/checkout@v7
        with:
          submodules: false # don't need submodules for testing

      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          name: ${{ env.ARTIFACT_FILE }}
          path: ${{ env.INSTALL_PATH }}

      - name: Extract artifact
        shell: bash
        run: |
          cd "$INSTALL_PATH"
          echo Contents of `pwd`:
          ls
          unzip "$ARTIFACT_FILE.zip"

      - name: Setup environment
        shell: bash
        run: |
          # install jack
          # even though SC on Windows doesn't use JACK directly
          # it will use JackRouter ASIO device
          curl -O -J -L https://github.com/jackaudio/jack2-releases/releases/download/v1.9.22/jack2-win64-v1.9.22.exe

          echo "installing JACK2"
          ./jack2-win64-v1.9.22.exe //TYPE="router" //SILENT //SUPPRESSMSGBOXES

          # add bin to PATH so that scsynth can be found
          echo "$INSTALL_PATH/SuperCollider" >> "$GITHUB_PATH"

          # start jack
          /c/Program\ Files/JACK2/jackd.exe --no-realtime -d dummy &

      - name: Run tests
        shell: bash

        # Windows return codes are broken in sclang. https://github.com/supercollider/supercollider/issues/7614.
        # Remove this once fixed.
        continue-on-error: true 
        run: $SCLANG --exclude-default-paths --include-path $INCLUDE_TEST --include-path $INCLUDE_CLASSLIB $SCRIPT_RUN_TESTS
