# -*- coding: utf-8 -*-
#
# SCons build system
# Copyright (C) 2008 Tim Blechmann
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; see the file COPYING.  If not, write to
# the Free Software Foundation, Inc., 59 Temple Place - Suite 330,
# Boston, MA 02111-1307, USA.

Import("env")

sources = Split("""buffer_manager.cpp
                   node_graph.cpp
                   dsp_context.cpp
                   memory_pool.cpp
                   server.cpp
                   sc_osc_handler.cpp
                   ../sc/sc_synth_prototype.cpp
                   ../sc/sc_plugin_interface.cpp
                   ../sc/sc_ugen_factory.cpp
                   ../sc/sc_synthdef.cpp
                   ../sc/sc_synth.cpp
                   ../utilities/thread.cpp
                   """)

sources = [File(x) for x in sources]

buildsource = env.Combine("build.cpp", sources)

binary_sources = Split("""main.cpp
                          """)

binary_sources = [File(x) for x in binary_sources]

binary_buildsource = env.Combine("binary_build.cpp", binary_sources)


Return("sources buildsource binary_sources binary_buildsource")
